package com.sunrise.dental.service;
import com.sunrise.dental.dto.*; import com.sunrise.dental.entity.*; import com.sunrise.dental.repository.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.math.*; import java.time.*; import java.util.*;
@Service public class ClinicService {
 final PatientRepository patients; final UserRepository users; final DentistRepository dentists; final TreatmentRepository treatments; final AppointmentRepository appointments; final AppointmentUpdateRepository updates; final BillRepository bills; final MailService mail;
 public ClinicService(PatientRepository p,UserRepository u,DentistRepository d,TreatmentRepository t,AppointmentRepository a,AppointmentUpdateRepository up,BillRepository b,MailService m){patients=p;users=u;dentists=d;treatments=t;appointments=a;updates=up;bills=b;mail=m;}
 private Patient findPatient(String id){return patients.findByIdNumberIgnoreCase(id.trim()).orElseThrow(()->new IllegalArgumentException("Patient ID number was not found."));}
 @Transactional public Patient createPatient(PatientRequest r,Long userId){if(patients.existsByIdNumberIgnoreCase(r.idNumber().trim()))throw new IllegalArgumentException("A patient with this ID number already exists.");Patient p=new Patient();p.setIdNumber(r.idNumber().trim().toUpperCase());p.setFullName(r.fullName().trim());p.setAddress(r.address().trim());p.setContactNumber(r.contactNumber().trim());p.setEmail(r.email());p.setGender(r.gender());p.setDateOfBirth(r.dateOfBirth());p.setEmergencyContact(r.emergencyContact());p.setAllergies(r.allergies());p.setMedicalNotes(r.medicalNotes());if(userId!=null)p.setUser(users.findById(userId).orElseThrow());return patients.save(p);}
 @Transactional public Patient updatePatient(String id,PatientRequest r){Patient p=findPatient(id);p.setFullName(r.fullName().trim());p.setAddress(r.address().trim());p.setContactNumber(r.contactNumber().trim());p.setEmail(r.email());p.setGender(r.gender());p.setDateOfBirth(r.dateOfBirth());p.setEmergencyContact(r.emergencyContact());p.setAllergies(r.allergies());p.setMedicalNotes(r.medicalNotes());return patients.save(p);}
 public Optional<Patient> lookup(String id){return patients.findByIdNumberIgnoreCase(id.trim());} public Optional<Patient> lookupByUserId(Long id){return patients.findByUserId(id);}
 public List<Treatment> treatments(){return treatments.findByActiveTrueOrderByNameAsc();}
 public List<Dentist> dentists(){return dentists.findAll().stream().filter(Dentist::isActive).toList();}
 @Transactional public Appointment book(AppointmentRequest r){Patient p=findPatient(r.patientIdNumber());Dentist d=dentists.findById(r.dentistId()).orElseThrow(()->new IllegalArgumentException("Dentist not found."));Treatment t=treatments.findById(r.treatmentId()).orElseThrow(()->new IllegalArgumentException("Treatment not found."));var start=r.appointmentDateTime().minusMinutes(30);var end=r.appointmentDateTime().plusMinutes(30);if(appointments.existsConflict(d.getId(),start,end,List.of(AppointmentStatus.BOOKED,AppointmentStatus.CONFIRMED)))throw new IllegalArgumentException("The dentist already has an appointment around this time.");Appointment a=new Appointment();a.setAppointmentNumber("SDC-"+UUID.randomUUID().toString().substring(0,8).toUpperCase());a.setPatient(p);a.setDentist(d);a.setTreatment(t);a.setAppointmentDateTime(r.appointmentDateTime());a.setPatientNote(r.patientNote());return appointments.save(a);}
 public List<Appointment> patientAppointments(String id){return appointments.findByPatientIdOrderByAppointmentDateTimeDesc(findPatient(id).getId());}
 public List<Appointment> dentistAppointments(Long userId){Dentist d=dentists.findByUserId(userId).orElseThrow(()->new IllegalArgumentException("Dentist profile not found."));return appointments.findByDentistIdOrderByAppointmentDateTimeAsc(d.getId());}
 @Transactional public AppointmentUpdate dentistUpdate(Long userId,Long appointmentId,AppointmentUpdateRequest r){Dentist d=dentists.findByUserId(userId).orElseThrow();Appointment a=appointments.findById(appointmentId).orElseThrow(()->new IllegalArgumentException("Appointment not found."));if(!a.getDentist().getId().equals(d.getId()))throw new IllegalArgumentException("You can only update your own appointments.");a.setStatus(r.status());a.setStaffNote(r.message());appointments.save(a);var u=new AppointmentUpdate();u.setAppointment(a);u.setDentist(d);u.setMessage(r.message());u.setEmailSent(mail.send(a.getPatient().getUser()!=null?a.getPatient().getUser().getEmail():a.getPatient().getEmail(),"Sunrise Dental - Appointment Update","Appointment "+a.getAppointmentNumber()+": "+r.message()));return updates.save(u);}
 public List<AppointmentUpdate> patientUpdates(String id){return updates.findByAppointmentPatientIdOrderByCreatedAtDesc(findPatient(id).getId());}
 public List<AppointmentUpdate> allUpdates(){return updates.findAllByOrderByCreatedAtDesc();}
 @Transactional public Bill createBill(BillRequest r){Appointment a=appointments.findById(r.appointmentId()).orElseThrow(()->new IllegalArgumentException("Appointment not found."));if(bills.findByAppointmentId(a.getId()).isPresent())throw new IllegalArgumentException("A bill already exists for this appointment.");BigDecimal subtotal=a.getTreatment().getDefaultPrice();BigDecimal discount=n(r.discount());BigDecimal tax=n(r.tax());BigDecimal total=subtotal.subtract(discount).add(tax);if(total.signum()<0)throw new IllegalArgumentException("Discount cannot exceed subtotal.");BigDecimal paid=n(r.paidAmount());if(paid.compareTo(total)>0)throw new IllegalArgumentException("Paid amount cannot exceed total.");Bill b=new Bill();b.setBillNumber("BILL-"+UUID.randomUUID().toString().substring(0,8).toUpperCase());b.setAppointment(a);b.setPatient(a.getPatient());b.setSubtotal(subtotal);b.setDiscount(discount);b.setTax(tax);b.setTotal(total);b.setPaidAmount(paid);b.setPaymentMethod(r.paymentMethod());b.setStatus(paid.signum()==0?BillStatus.UNPAID:(paid.compareTo(total)==0?BillStatus.PAID:BillStatus.PARTIALLY_PAID));return bills.save(b);}
 private BigDecimal n(BigDecimal x){return x==null?BigDecimal.ZERO:x.setScale(2,RoundingMode.HALF_UP);}
 public List<Bill> patientBills(String id){return bills.findByPatientIdOrderByCreatedAtDesc(findPatient(id).getId());}
 public List<Appointment> allAppointments(){return appointments.findAll(org.springframework.data.domain.Sort.by("appointmentDateTime").descending());}
}
