import{useEffect,useState}from'react';import{useNavigate,useParams}from'react-router-dom';import api from'../services/api';

export default function Payment(){
 const{appointmentId}=useParams();const nav=useNavigate();const[p,setP]=useState(null);const[method,setMethod]=useState('CASH');
 const[card,setCard]=useState({name:'',number:'',expiry:'',cvv:''});const[s,setS]=useState('');const[loading,setLoading]=useState(false);const[done,setDone]=useState(null);
 useEffect(()=>{api.get('/appointments/'+appointmentId+'/billing-preview').then(x=>setP(x.data)).catch(e=>setS(e.response?.data?.message||'Unable to load appointment billing details.'));},[appointmentId]);
 const pay=async e=>{e.preventDefault();setS('');
  if(method==='CARD'){if(card.name.trim().length<2||!/^\d{16}$/.test(card.number.replace(/\s/g,''))||!/^\d{2}\/\d{2}$/.test(card.expiry)||!/^\d{3,4}$/.test(card.cvv)){setS('Please enter valid card details. This is a secure interface demonstration; no card data is stored.');return}}
  setLoading(true);
  try{const x=await api.post('/payments',{appointmentId:Number(appointmentId),paymentMethod:method,cardholderName:method==='CARD'?card.name:null,cardLast4:method==='CARD'?card.number.replace(/\s/g,'').slice(-4):null});setDone(x.data);setS('Payment completed successfully. A receipt has been sent to your registered email address when email service is enabled.');}
  catch(e){setS(e.response?.data?.message||'Payment could not be completed.')}finally{setLoading(false)}
 };
 const download=async()=>{try{const r=await api.get('/payments/'+done.id+'/receipt',{responseType:'blob'});const url=URL.createObjectURL(r.data);const a=document.createElement('a');a.href=url;a.download='Sunrise-Dental-Receipt.pdf';a.click();URL.revokeObjectURL(url);}catch(e){setS('Unable to download receipt.')}};
 if(done)return <div className="app"><header><b>✦ PAYMENT CONFIRMED</b><a href="/dashboard">Dashboard</a></header><main><div className="panel payment-success"><div className="success-icon">✓</div><h1>Payment Successful</h1><p>Your appointment has been reserved and your payment has been recorded.</p><div className="receipt-summary"><div><span>Payment reference</span><b>{done.transactionReference}</b></div><div><span>Amount paid</span><b>Rs. {Number(done.amount).toLocaleString(undefined,{minimumFractionDigits:2})}</b></div><div><span>Payment method</span><b>{done.paymentMethod}</b></div></div><div className="payment-actions"><button onClick={download}>Download PDF Receipt</button><button className="secondary" onClick={()=>nav('/appointments')}>View My Appointments</button></div><p>{s}</p></div></main></div>;
 if(!p)return <div className="app"><header><b>✦ BILLING & PAYMENT</b><a href="/appointments">Appointments</a></header><main><div className="panel"><h1>Preparing your bill...</h1><p>{s}</p></div></main></div>;
 return <div className="app"><header><b>✦ BILLING & PAYMENT</b><a href="/appointments">Appointments</a></header><main><div className="payment-layout">
  <section className="panel"><h1>Appointment Payment</h1><p>Review your appointment charges before confirming payment.</p>
   <div className="bill-lines"><div><span>Treatment</span><b>{p.treatmentName}</b></div><div><span>Treatment fee</span><b>Rs. {Number(p.treatmentFee).toLocaleString(undefined,{minimumFractionDigits:2})}</b></div><div><span>Consultation fee</span><b>Rs. {Number(p.consultationFee).toLocaleString(undefined,{minimumFractionDigits:2})}</b></div><div><span>Discount</span><b>- Rs. {Number(p.discount).toLocaleString(undefined,{minimumFractionDigits:2})}</b></div><div><span>Tax</span><b>Rs. {Number(p.tax).toLocaleString(undefined,{minimumFractionDigits:2})}</b></div><div className="bill-total"><span>Total</span><b>Rs. {Number(p.total).toLocaleString(undefined,{minimumFractionDigits:2})}</b></div></div>
  </section>
  <section className="panel"><h2>Choose Payment Method</h2><div className="payment-methods"><button type="button" className={method==='CASH'?'selected':''} onClick={()=>setMethod('CASH')}>Cash</button><button type="button" className={method==='CARD'?'selected':''} onClick={()=>setMethod('CARD')}>Credit / Debit Card</button></div>
   <form className="payment-form" onSubmit={pay}>{method==='CARD'&&<div className="card-form"><label>Cardholder name<input required value={card.name} onChange={e=>setCard({...card,name:e.target.value})} placeholder="Name on card"/></label><label>Card number<input required maxLength="19" inputMode="numeric" value={card.number} onChange={e=>setCard({...card,number:e.target.value.replace(/\D/g,'').slice(0,16).replace(/(.{4})/g,'$1 ').trim()})} placeholder="1234 5678 9012 3456"/></label><div className="card-row"><label>Expiry<input required maxLength="5" value={card.expiry} onChange={e=>{let v=e.target.value.replace(/\D/g,'').slice(0,4);if(v.length>2)v=v.slice(0,2)+'/'+v.slice(2);setCard({...card,expiry:v})}} placeholder="MM/YY"/></label><label>CVV<input required type="password" maxLength="4" inputMode="numeric" value={card.cvv} onChange={e=>setCard({...card,cvv:e.target.value.replace(/\D/g,'').slice(0,4)})} placeholder="•••"/></label></div><p className="security-note">Demo payment interface: full card number and CVV are never sent to or stored by this clinic system.</p></div>}
   <button className="pay-button" disabled={loading}>{loading?'Processing payment...':method==='CARD'?'Pay Securely':'Confirm Cash Payment'}</button><p>{s}</p></form>
  </section>
 </div></main></div>
}
