import{useEffect,useState}from'react';
import api from'../services/api';

export default function StaffAppointments(){
 const[d,setD]=useState([]),[selected,setSelected]=useState(''),[a,setA]=useState([]),[s,setS]=useState('');
 const[loading,setLoading]=useState(false);
 useEffect(()=>{api.get('/dentists').then(x=>setD(x.data)).catch(()=>setS('Unable to load dentists.'));},[]);
 const search=async e=>{e.preventDefault();if(!selected){setS('Select a dentist to view appointments.');setA([]);return}setLoading(true);setS('');try{const x=await api.get('/staff/dentists/'+selected+'/appointments');setA(x.data);setS(x.data.length?'Appointments loaded successfully.':'No appointments found for this dentist.');}catch(e){setA([]);setS(e.response?.data?.message||'Unable to load appointments.')}finally{setLoading(false)}};
 return <div className="app"><header><b>✦ DENTIST APPOINTMENT SCHEDULE</b><a href="/dashboard">Dashboard</a></header><main><div className="panel"><h1>Appointments by Dentist</h1><p>Reception staff can select a dentist to review all appointments assigned to that dentist. Patient and payment details are shown for front-desk support.</p><form className="lookup staff-dentist-search" onSubmit={search}><select required value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Select dentist</option>{d.map(x=><option value={x.id} key={x.id}>{x.fullName} · {x.specialization}</option>)}</select><button disabled={loading}>{loading?'Loading...':'View Appointments'}</button></form><p>{s}</p></div>{a.length>0&&<div className="panel"><div className="panel-heading-row"><div><h2>Scheduled Appointments</h2><p>{d.find(x=>String(x.id)===String(selected))?.fullName||'Selected dentist'}</p></div></div><div className="staff-appointment-table">{a.map(x=><div className="staff-appointment-row" key={x.id}><div><b>{x.appointmentNumber}</b><small>{String(x.appointmentDateTime||'').replace('T',' ')}</small></div><div><b>{x.patient?.fullName||'Patient'}</b><small>{x.patient?.idNumber||'NIC not available'}</small></div><div><b>{x.treatment?.name||'Treatment'}</b><small>Rs. {Number(x.treatment?.defaultPrice||0).toLocaleString(undefined,{minimumFractionDigits:2})}</small></div><span className={'appointment-status '+String(x.status).toLowerCase()}>{x.status}</span></div>)}</div></div>}</main></div>
}
